Graph generation
ros-navigation/docs.nav2.org pull request #401
Opened 2023-03-13 13:36 UTC by jwallace42

This PR adds a tutorial for graph generation. This graph is designed to be consumed by the nav2_route. 

The sql script for id association can be found [here](https://github.com/jwallace42/qgis-maps/blob/main/sql/generate_start_and_end_id.sql). 

I would suggest creating a ROS Planning repository that holds the QGIS data. This will allow us to make quick changes to current graphs and store plugins that automate the graph generation. 

https://github.com/jwallace42/qgis-maps/tree/main

2023-03-14 16:47 UTC, SteveMacenski requested changes

2023-03-14 16:47 UTC, SteveMacenski commented on tutorials/docs/graph_generation.rst
> +    :height: 400px
Alot of these images are warped - if you specify the height and the width, it'll use those exactly even if the image isn't those dimensions or proportions. Try just setting the width for all images

2023-03-14 16:47 UTC, SteveMacenski commented on tutorials/docs/graph_generation.rst
> +1- Open QGIS and create a new project. Set the project coordinate reference system to `WGS 84/ Pseudo-Mercator`.
Why those values? Please explain

2023-03-14 16:47 UTC, SteveMacenski commented on tutorials/docs/graph_generation.rst
> +3- If you need to adjust your raster image to the map frame, open the georeferencer tool
I don't really understand any of the instructions after this in point 3. What are these control points? What is this actually doing and why?

2023-03-14 16:47 UTC, SteveMacenski commented on tutorials/docs/graph_generation.rst
> +Click on the edge layer and use the tool bar to start adding edges. Use the magnet tool to snap
Same question: how/what tool to use for adding edges

2023-03-14 16:47 UTC, SteveMacenski commented on tutorials/docs/graph_generation.rst
> +Select the node layer and then click on the `Field calculator` tool. Check the `Update existing
Where is the field calculator tool?

2023-03-14 16:47 UTC, SteveMacenski commented on tutorials/docs/graph_generation.rst
> +This will generate ids for each node. To verify that the ids have been generated, right click on
I assume this generates the ndoe ids as the row number, please be specific about how the nodes are numbered here

2023-03-14 16:47 UTC, SteveMacenski commented on tutorials/docs/graph_generation.rst
> +the node layer and select `Open attribute table`. This will display the current attributes associated with the node layer.
Is there a reason we can't set this before adding the nodes so that they're auto populated when we add them initially?

2023-03-14 16:47 UTC, SteveMacenski commented on tutorials/docs/graph_generation.rst
> +Follow the same process for the edges but swap the `@row_number` for `@row_number + <number_of_nodes>`.
What if the number of nodes changes? We want to keep edges IDs even if we add new nodes because then all of our semantic data is nulled out. If we expand a map or add new nodes, we need to not rename edges already made in a previous session

2023-03-14 16:47 UTC, SteveMacenski commented on tutorials/docs/graph_generation.rst
> +Select `Database -> DB manager`. Expand `Virtual layers` and expand `Project layers`. Open up
How do you open the sql window? What script to load?

2023-03-14 16:47 UTC, SteveMacenski commented on tutorials/docs/graph_generation.rst
> +Select `Database -> DB manager`. Expand `Virtual layers` and expand `Project layers`. Open up
What is this doing? Tell the reader

2023-03-14 16:47 UTC, SteveMacenski commented on tutorials/docs/graph_generation.rst
> +from the connected edges geojson file into the features tag in the graph file.
Can't we export them together?

2023-03-14 16:47 UTC, SteveMacenski commented
Is there a reason not to have the sql script in the nav2_route package?

2023-03-14 21:33 UTC, jwallace42 commented on tutorials/docs/graph_generation.rst
> +3- If you need to adjust your raster image to the map frame, open the georeferencer tool
By default QGIS places the top left corner of the raster image at (0,0) with the y axis pointing down. If you want to place coordinates in the "map" frame the image needs to be transformed. Otherwise, you can define the static transform.

2023-03-14 21:43 UTC, jwallace42 commented on tutorials/docs/graph_generation.rst
> +the node layer and select `Open attribute table`. This will display the current attributes associated with the node layer.
We can using auto incrementing. Do we want to switch to that?

2023-03-14 21:44 UTC, jwallace42 commented on tutorials/docs/graph_generation.rst
> +Follow the same process for the edges but swap the `@row_number` for `@row_number + <number_of_nodes>`.
We can bump this to a intial number choosen by the user.

2023-03-14 21:47 UTC, jwallace42 commented on tutorials/docs/graph_generation.rst
> +Select `Database -> DB manager`. Expand `Virtual layers` and expand `Project layers`. Open up
I mention above that we can associate the node IDs with the edge IDs. Is there more information needed?

2023-03-14 21:51 UTC, jwallace42 commented
> Is there a reason not to have the sql script in the nav2_route package?

We need the QGIS files to easily modify the graph. I would suggest that that script stays with the QGIS graphs repo https://github.com/jwallace42/qgis-maps.

2023-03-15 22:25 UTC, jwallace42 commented on tutorials/docs/graph_generation.rst
> +from the connected edges geojson file into the features tag in the graph file.
Just completed this https://github.com/jwallace42/qgis-maps/blob/main/scripts/export_shapefiles.py

2023-03-16 16:58 UTC, jwallace42 commented on tutorials/docs/graph_generation.rst
> +the node layer and select `Open attribute table`. This will display the current attributes associated with the node layer.
(switched)

2023-03-16 17:00 UTC, jwallace42 commented on tutorials/docs/graph_generation.rst
> +Select `Database -> DB manager`. Expand `Virtual layers` and expand `Project layers`. Open up
> How do you open the sql window? What script to load?

The script currently in my repo. I am not quite sure how we want to handle that.

2023-03-18 00:41 UTC, SteveMacenski commented on tutorials/docs/graph_generation.rst
> +Select `Database -> DB manager`. Expand `Virtual layers` and expand `Project layers`. Open up
Put into the Route Server package, I think

2023-03-18 00:42 UTC, SteveMacenski commented on tutorials/docs/graph_generation.rst
> +Follow the same process for the edges but swap the `@row_number` for `@row_number + <number_of_nodes>`.
What if new ones are added? Are even old nodes potentially renumbered if new ones are added later?

2023-03-18 00:45 UTC, SteveMacenski commented on tutorials/docs/graph_generation.rst
> +3- If you need to adjust your raster image to the map frame, open the georeferencer tool
Don't explain to me - explain in the tutorial :smile:  Also explain the relatinoship between the map origin and the "transform" happening here, I don't think you ever explicitly state this or how to set the  values explicitly

2023-03-18 00:45 UTC, SteveMacenski commented on tutorials/docs/graph_generation.rst
> +3- If you need to adjust your raster image to the map frame, open the georeferencer tool
Don't explain to me - explain in the tutorial :smile:  Also explain the relatinoship between the map origin and the "transform" happening here, I don't think you ever explicitly state this or how to set the  values explicitly

2023-03-18 00:48 UTC, SteveMacenski requested changes

2023-03-18 00:48 UTC, SteveMacenski commented on tutorials/docs/route_graph_generation.rst
> +Within the `Expression Dialog` select `Import user expressions` and import `increment_node_id.json`. Expand `User expressions` and double click on `increment_node_id`.
Where is `increment_node_id.json`, where do I get it? Where does it live?

2023-03-18 00:48 UTC, SteveMacenski commented on tutorials/docs/route_graph_generation.rst
> +Within the `Expression Dialog` select `Import user expressions` and import `increment_node_id.json`. Expand `User expressions` and double click on `increment_node_id`.
Same with any of these new files / info

2023-03-18 00:48 UTC, SteveMacenski commented on tutorials/docs/graph_generation.rst
> +Click on the node layer and use the tool bar to start adding nodes. The IDs field can be left null.
Have an arrow pointing to it or something

2023-04-04 19:49 UTC, jwallace42 commented
@SteveMacenski if you get a chance to review this week that would be great. Otherwise, I might forget what I did :).

2023-04-17 17:19 UTC, SteveMacenski requested changes
Much, much improved!!

2023-04-17 17:19 UTC, SteveMacenski commented on tutorials/docs/route_graph_generation.rst
> +The first control point we could select is (0, -200) -> (0,0). (0, -200) is the bottom left corner in the pixel frame and (0, 0) is coordinates in the spatial frame.
Is that an instruction to set `(0, -200)` to `(0,0)`? Make it clear that you're asking them to do something. Is that automatically set / detected? Or do they have to type in (0,0)?

2023-04-17 17:19 UTC, SteveMacenski commented on tutorials/docs/route_graph_generation.rst
> +For the second control point we will select the top left corner of the image (0,0). The associated coordinates in the spatial frame can be calculated by using the resolution
```suggestion
For the second control point we will select the top left corner of the image as the original (0,0). The associated coordinates in the spatial frame can be calculated by using the resolution 
```

2023-04-17 17:19 UTC, SteveMacenski commented on tutorials/docs/route_graph_generation.rst
> +to convert the pixels to meters. In this case, (0, 0) -> (0, 10). Where 10 m is 200 * 0.05. The last control will be the bottom right corner. (200,-200) -> (5, 0).
```suggestion
to convert the pixels to meters. In this case, (0, 0) -> (0, 10). Where 10 m is 200 * 0.05. The last control will be the bottom right corner: (200,-200) -> (5, 0). 
```

2023-04-17 17:19 UTC, SteveMacenski commented on tutorials/docs/route_graph_generation.rst
> +The first control point we could select is (0, -200) -> (0,0). (0, -200) is the bottom left corner in the pixel frame and (0, 0) is coordinates in the spatial frame.
Make it clear we're setting it into meters space, not pixel coordinate space. 0,0 is ambiguous for units and the later ones are talking about meters so it would be good to clarify that up front

2023-04-17 17:19 UTC, SteveMacenski commented on tutorials/docs/route_graph_generation.rst
> +.. note::
Move this before the example

2023-04-17 17:19 UTC, SteveMacenski commented on tutorials/docs/route_graph_generation.rst
> +Select the raster image you wish to georeference and place control point by selecting the icon next to the `Transformation Settings` and clicking on the raster image.
Icon of what? Where - what screen?

2023-04-17 17:19 UTC, SteveMacenski commented on tutorials/docs/route_graph_generation.rst
> +by selecting `Start Transformation`.
What button? does it lierally say "start transformation"? I don't see that on the images provided. If there's an icon, show me or tell me what it is (or have an arrow pointing to it in the graphic)

2023-04-17 17:19 UTC, SteveMacenski commented on tutorials/docs/route_graph_generation.rst
> +    To see the directionality of the edges, right click on the edge layer and select `Properties`. Click `Symbology -> Simple Line` and change the `Symbol layer type` to `Arrow`.
Actually, don't have this be a footnote later, have them set this up, up front . Its important to know directionality since there are no bi-directional edges.

2023-04-17 21:44 UTC, jwallace42 commented on tutorials/docs/graph_generation.rst
> +Follow the same process for the edges but swap the `@row_number` for `@row_number + <number_of_nodes>`.
> By default, if a node deleted the id list will not be updated. It is up to the user to determine how they wish to update the ids if individual
    or multiple nodes are deleted. Any node that is added will contiune to increment based on the highest id. This value can be overwriten by the user 

I wrote the note above below section 3.

2023-04-17 21:45 UTC, jwallace42 commented on tutorials/docs/graph_generation.rst
> +Select `Database -> DB manager`. Expand `Virtual layers` and expand `Project layers`. Open up
All the scripts should be in the route server package now. 

https://github.com/ros-planning/navigation2/pull/3490

2023-04-17 22:28 UTC, jwallace42 commented on tutorials/docs/route_graph_generation.rst
> +Click on the node layer and then on the pencil icon to start editing the layer. To add points, click on `Add points feature`. Start adding nodes by clicking in the main window.
I described the icon. If that doesn't work I will add an arrow.

2023-04-17 22:29 UTC, jwallace42 commented on tutorials/docs/route_graph_generation.rst
> +Click on the edge layer and then on the pencil icon to start editing the layer. To add edges, click on `Add Line feature`. Start adding edges by clicking twice in the main window.
same as above.

2023-04-17 22:29 UTC, jwallace42 commented on tutorials/docs/route_graph_generation.rst
> +    :height: 1922px
yeahhhh fixed

2023-04-17 22:29 UTC, jwallace42 commented on tutorials/docs/route_graph_generation.rst
> +    To see the directionality of the edges, right click on the edge layer and select `Properties`. Click `Symbology -> Simple Line` and change the `Symbol layer type` to `Arrow`.
I moved this up.

2023-04-18 15:45 UTC, SteveMacenski commented on tutorials/docs/route_graph_generation.rst
> +Click on the edge layer and then on the pencil icon to start editing the layer. To add edges, click on `Add Line feature`. Start adding edges by clicking twice in the main window.
Ok... but you should still actually tell the users what the button is called...  I think you should keep the text in line as you had before and add an arrow to the image to show where it is, that's the most clear.

2023-04-18 15:46 UTC, SteveMacenski commented on tutorials/docs/route_graph_generation.rst
> +Click on the node layer and then on the pencil icon to start editing the layer. To add points, click on `Add points feature`. Start adding nodes by clicking in the main window.
Ok... but you should still actually tell the users what the button is called... I think you should keep the text in line as you had before and add an arrow to the image to show where it is, that's the most clear.

2023-04-18 18:43 UTC, jwallace42 commented on tutorials/docs/graph_generation.rst
> + .. image:: images/graph_generation/node_layer.png
It is the default for the id type and a new layer is created. The user doesn't have to add it.

2023-04-27 17:32 UTC, SteveMacenski commented on tutorials/docs/route_graph_generation.rst
> +1- Open QGIS and create a new project by selecting `Project->New`. Save your project by selecting, `Project -> Save As`.
I didn't mention this before since its a final cleanup thing but we're at this point now: For all the numbered steps, make them subsections. If you use the `-----` header type, then it'll fall under the Tutorial Steps section but be more easily pronounced.

So like 
```
1- Create New QGIS Project
----------------------------------
```

or 

```
2- Setup Coordinate System
-------------------------------------
```

2023-04-27 17:32 UTC, SteveMacenski commented on tutorials/docs/route_graph_generation.rst
> +Select the raster image you wish to georeference and place control point by selecting `Add Point ` and clicking on the raster image.
```suggestion
Select the raster image you wish to georeference and place control point by selecting `Add Point` and clicking on the raster image. 
```

I think this caused some rendering problems

2023-04-27 22:05 UTC, SteveMacenski approved these changes
Done - just waiting for server to be released to merge. You can remove this from your queue :-)

2025-03-28 22:54 UTC, SteveMacenski commented on tutorials/docs/route_graph_generation.rst
> +Drag and drop the georeferenced raster file into the layers window.
```suggestion
Close the window. Drag and drop the georeferenced raster file that was just created into the layers window. This should be a tiff file, by default.
```

2025-03-28 22:54 UTC, SteveMacenski commented on tutorials/docs/route_graph_generation.rst
> +(First point is start, second point is end). Press `Esc` when you have finished adding the two points.
```suggestion
(First point is start, second point is end). Press right click anywhere when you have finished adding the two points for the prompt to save to come up.
The edge locations must exactly match up to the node locations, so if Snapping is not already enabled by default, enable it via Views->Toolbars->Snapping Toolbar and depress the Magnet icon.
```

2025-03-28 22:55 UTC, merged