initial commit
ros-navigation/docs.nav2.org pull request #532
Opened 2024-03-04 21:37 UTC by stevedanomodolor

Updates https://github.com/ros-planning/navigation2/pull/4019

2024-03-05 00:44 UTC, SteveMacenski requested changes

2024-03-05 00:44 UTC, SteveMacenski commented on configuration/packages/smac/configuring-smac-hybrid.rst
> +    Goal heading mode enum string to plan goal with multiple orientation. Options are "DEFAULT", "BIDIRECTIONAL" and "ALL_DIRECTION
Missing the last `"` and probably would be good to explain what those options mean. Ditto in other config guide files

2024-03-05 00:44 UTC, SteveMacenski commented on migration/Iron.rst
> +# (todo) add image
TODO

2024-03-11 19:20 UTC, SteveMacenski requested changes

2024-03-11 19:20 UTC, SteveMacenski commented on configuration/packages/smac/configuring-smac-hybrid.rst
> +    Goal heading mode enum string to plan goal with multiple orientation. Options are "DEFAULT", "BIDIRECTIONAL" and "ALL_DIRECTION
@stevedanomodolor these are still missing

2024-03-12 06:16 UTC, stevedanomodolor commented on configuration/packages/smac/configuring-smac-hybrid.rst
> +    Goal heading mode enum string to plan goal with multiple orientation. Options are "DEFAULT", "BIDIRECTIONAL" and "ALL_DIRECTION
I did make the changes but i forgot to push it jjajaj, my bad

2024-03-12 18:28 UTC, SteveMacenski approved these changes

2025-01-28 20:32 UTC, SteveMacenski requested changes

2025-01-28 20:32 UTC, SteveMacenski commented on configuration/packages/smac/configuring-smac-hybrid.rst
> +    Number of goal heading bins to skip during the coarse search phase of planning. When a goal is found, a fine search is performed to determine the exact path. This parameter is only used when the
"Number of goal heading bins to skip during the coarse search phase of analytic expansion goal-finding. When a goal is found, a fine search is performed to determine the exact path during full-resolution. This parameter is only used when the goal heading mode is set to "ALL_DIRECTION" and It helps to reduce search time of analytic expansions."

2025-01-28 20:32 UTC, SteveMacenski commented on migration/Iron.rst
>  *******************************************
I think now this should be in the Jazzy file

2025-01-28 20:32 UTC, SteveMacenski commented on configuration/packages/smac/configuring-smac-lattice.rst
> +    Number of goal heading bins to skip during the coarse search phase of planning. When a goal is found, a fine search is performed to determine the exact path. This parameter is only used when the
Update here as well, but I think the default for Lattice should be the number of angular bins, instead. These are typically 16 or 32, which are reasonable to do at full resolution (but can still give the option to do coarser if they do have control sets with 64+ bins). I'd also add in specifically for the lattice config guide that it is recommended to only do coarser search if the number of bins are > 24

2025-01-28 23:59 UTC, stevedanomodolor commented on configuration/packages/smac/configuring-smac-lattice.rst
> +    Number of goal heading bins to skip during the coarse search phase of planning. When a goal is found, a fine search is performed to determine the exact path. This parameter is only used when the
so you recommend the default values be 1 then?, I don't follow when you mean that coarse search resolution should be the same number as the angular bins

2025-01-29 00:00 UTC, stevedanomodolor commented on migration/Iron.rst
>  *******************************************
done

2025-01-29 00:00 UTC, stevedanomodolor commented on configuration/packages/smac/configuring-smac-hybrid.rst
> +    Number of goal heading bins to skip during the coarse search phase of planning. When a goal is found, a fine search is performed to determine the exact path. This parameter is only used when the
done

2025-01-29 19:36 UTC, SteveMacenski commented on migration/Jazzy.rst
> +*******************************************
`**` need to match the line size :-)

2025-01-29 19:36 UTC, SteveMacenski commented on configuration/packages/smac/configuring-smac-lattice.rst
> +    Number of goal heading bins to skip during the coarse search phase of planning. When a goal is found, a fine search is performed to determine the exact path. This parameter is only used when the
Yeah, the default for lattice should be `1` so we use all 16 bins out of the box for all directions (since 16 is still small enough)

2025-02-03 05:09 UTC, stevedanomodolor commented on migration/Jazzy.rst
> +*******************************************
made the changes

2025-02-03 05:09 UTC, stevedanomodolor commented on configuration/packages/smac/configuring-smac-lattice.rst
> +    Number of goal heading bins to skip during the coarse search phase of planning. When a goal is found, a fine search is performed to determine the exact path. This parameter is only used when the
made the changes

2025-02-04 00:38 UTC, SteveMacenski approved these changes

2025-02-04 00:38 UTC, SteveMacenski commented on configuration/packages/smac/configuring-smac-lattice.rst
> +    Number of goal heading bins to skip during the coarse search phase of analytic expansion goal-finding. When a goal is found, a fine search is performed to determine the exact path during full-res
```suggestion
    Number of goal heading bins to skip during the coarse search phase of analytic expansion goal-finding. When a goal is found, a fine search is performed to determine the exact path during full-resolution. This parameter is only used when the goal heading mode is set to "ALL_DIRECTION" and It helps to reduce search time of analytic expansions. g the coarse search phase of analytic expansion goal-finding. When a goal is found, a fine search is performed to determine the exact path during full-resolution. This parameter is only used when the goal heading mode is set to "ALL_DIRECTION" and it helps to reduce search time of analytic expansions. It is recommended to only do coarser search if the number of bins are > 24. Otherwise, leave as 1 (fine search).
```

2025-04-29 23:58 UTC, SteveMacenski approved these changes

2025-04-30 06:11 UTC, merged