Add .pre-commit-config.yaml and codespell_word, fixed spellchecks accordingly
ros-navigation/docs.nav2.org pull request #581
Opened 2024-08-13 08:19 UTC by cschindlbeck

Added a .pre-commit-config.yaml and fixed spelling errors

2024-08-13 14:16 UTC, SteveMacenski requested changes
Thanks!  A few fixes needed for formatting

2024-08-13 14:16 UTC, SteveMacenski commented on configuration/packages/bt-plugins/actions/TruncatePath.rst
>  -----------
Needs another `-` as well for rst formatting

2024-08-13 14:16 UTC, SteveMacenski commented on configuration/packages/bt-plugins/actions/TruncatePathLocal.rst
>  -----------
Ditto

2024-08-13 14:16 UTC, SteveMacenski commented on plugin_tutorials/docs/writing_new_behavior_plugin.rst
> +|                      | this method should implement operations which are necessary before the     |                         |
For all 3: the table formatting needs to be restored

2024-08-13 14:16 UTC, SteveMacenski commented on plugin_tutorials/docs/writing_new_nav2controller_plugin.rst
> +|                           | should implement operations which are necessary before controller goes to an active  |                        |
Ditto

2024-08-13 14:16 UTC, SteveMacenski commented on plugin_tutorials/docs/writing_new_nav2planner_plugin.rst
> +|                      | method should implement operations which are necessary before planner goes |                         |
Ditto

2024-08-13 14:16 UTC, SteveMacenski commented on plugin_tutorials/docs/writing_new_navigator_plugin.rst
> -|                           | should implement operations which are neccessary before navigator goes to an active   |                        |
Ditto

2024-08-13 14:16 UTC, SteveMacenski commented on plugins/index.rst
> +|`ThetaStarPlanner`_        | Anshumaan Singh                       | An implementation of Theta*   | Differential,       |
ditto

2024-08-13 14:16 UTC, SteveMacenski commented on tutorials/docs/navigation2_on_real_turtlebot3.rst
>  ----------------------------------
Ditto

2024-08-14 05:08 UTC, cschindlbeck commented on plugins/index.rst
> +|`ThetaStarPlanner`_        | Anshumaan Singh                       | An implementation of Theta*   | Differential,       |
in this file, another big table had to be adjusted, please check

2024-08-14 05:20 UTC, cschindlbeck commented on .codespell_words
> +priorization
Should this be kept? According to various sources, the correct word is prioritization.

2024-08-14 15:35 UTC, SteveMacenski commented on .codespell_words
> +priorization
I'm not sure exactly where its used, but yeah I think that is the correct word

2024-08-14 15:35 UTC, SteveMacenski commented on .pre-commit-config.yaml
> +# To use:
Is there a way to have this run as a CI github action? I don't want it to auto-fix on committing to `master` (since that could de-format tables and headers) but it would be nice to have awareness of when PRs are opened.

2024-08-15 06:28 UTC, cschindlbeck commented on .codespell_words
> +priorization
Fixed it

2024-08-15 06:31 UTC, cschindlbeck commented on .pre-commit-config.yaml
> +# To use:
I have integrated a CI github action like this, so the CI will be marked as failed and then the contributor must commit manually in order to prevent misalignement of tables which is done in the review as here

2024-08-15 14:36 UTC, SteveMacenski commented
Oooo neat, thanks!

2024-08-15 14:36 UTC, merged