Document bt_navigator error_code_name_prefixes and error_msg
ros-navigation/docs.nav2.org pull request #587
Opened 2024-08-31 10:17 UTC by aosmw

2024-09-04 16:48 UTC, SteveMacenski requested changes
Largely LGTM

2024-09-04 16:48 UTC, SteveMacenski commented on behavior_trees/trees/nav_to_pose_and_pause_near_goal_obstacle.rst
> +              <FollowPath path="{path}" controller_id="{selected_controller}" error_code_id="{follow_path_error_code}" error_msg="{follow_path_error_msg}"/>
This BT missing the spin/backup error_msg?

2024-09-04 16:48 UTC, SteveMacenski commented on behavior_trees/trees/nav_to_pose_with_consistent_replanning_and_if_path_becomes_invalid.rst
> +            <FollowPath path="{path}" controller_id="{selected_controller}" error_code_id="{follow_path_error_code}" error_msg="{follow_path_error_msg}"/>
This BT missing the spin/backup error_msg?

2024-09-04 16:48 UTC, SteveMacenski commented on migration/Jazzy.rst
> +BehaviorTree error_msg
Move this to the top, this is an important first note for changes required for users

2024-09-04 16:48 UTC, SteveMacenski commented on migration/Jazzy.rst
> +A new parameter for the BT Navigator "error_code_name_prefixes" was introduced.  It replaces the "error_code_id_names" parameter to support both an error code and an associated error message.  Behavi
```suggestion
A new parameter for the BT Navigator "error_code_name_prefixes" was introduced.  It replaces the "error_code_id_names" parameter to support both an error code and an associated error message.  Behavior tree elements that support an "error_code_id" and "error_msg" attribute, must have values that use the corresponding prefix with the suffix "_error_code" and "_error_msg" respectively. The error messages can then be viewed by applications calling Nav2 or its servers for handling specific errors with more contextual information than simply the error code.
```

2024-09-07 02:50 UTC, aosmw commented on behavior_trees/trees/nav_to_pose_with_consistent_replanning_and_if_path_becomes_invalid.rst
> +            <FollowPath path="{path}" controller_id="{selected_controller}" error_code_id="{follow_path_error_code}" error_msg="{follow_path_error_msg}"/>
Done, although, spin and backup are not in the default list of `error_code_name_prefixes`.  Do you want them added along with all builtin actions?

```
  std::vector<std::string> error_code_name_prefixes = {
    "follow_path",
    "compute_path",
  };
```

https://github.com/ros-navigation/navigation2/blob/52e7a79cbc7adc9e9fc7634dc26cc064e46eab97/nav2_behavior_tree/include/nav2_behavior_tree/bt_action_server_impl.hpp#L76C1-L80C1

2024-09-07 02:50 UTC, aosmw commented on migration/Jazzy.rst
> +BehaviorTree error_msg
done.

2024-09-07 02:51 UTC, aosmw commented on behavior_trees/trees/nav_to_pose_and_pause_near_goal_obstacle.rst
> +              <FollowPath path="{path}" controller_id="{selected_controller}" error_code_id="{follow_path_error_code}" error_msg="{follow_path_error_msg}"/>
Done

2024-09-07 02:52 UTC, aosmw commented on migration/Jazzy.rst
> +A new parameter for the BT Navigator "error_code_name_prefixes" was introduced.  It replaces the "error_code_id_names" parameter to support both an error code and an associated error message.  Behavi
Done.

2024-09-09 17:18 UTC, SteveMacenski approved these changes

2025-02-04 01:50 UTC, SteveMacenski commented on migration/Jazzy.rst
> +Thus, users must update their ``nav2_params.yaml`` to include this new format of specifying error message and code locations.
Please provide the example replacement YAML to:

```
    error_code_name_prefixes:
      - compute_path
      - follow_path
 ```
 from
```
    error_code_names:
      - compute_path_error_code
      - follow_path_error_code
```

To be clear to users what this means, this is a pretty key 'mess up' alot of people will make without very clear instructions.

2025-02-08 10:28 UTC, ewak commented on migration/Jazzy.rst
> +Thus, users must update their ``nav2_params.yaml`` to include this new format of specifying error message and code locations.
I have had a go at the content of this.  I need to check how it looks when built.

2025-02-08 10:48 UTC, ewak commented on migration/Jazzy.rst
> +Thus, users must update their ``nav2_params.yaml`` to include this new format of specifying error message and code locations.
Still needs work.

https://output.circle-artifacts.com/output/job/b81c6114-a83c-4c85-a536-d76e061bf658/artifacts/0/html/migration/Jazzy.html

2025-02-08 12:10 UTC, ewak commented on migration/Jazzy.rst
> +Thus, users must update their ``nav2_params.yaml`` to include this new format of specifying error message and code locations.
Ok happier now this and ready for review.

2025-02-11 01:31 UTC, SteveMacenski requested changes

2025-02-11 01:31 UTC, SteveMacenski commented on configuration/packages/configuring-bt-navigator.rst
> +    List of of error code name prefixes to be appended with '_error_code' and searched for during aborted navigator error processing.
I thin kwe should leave the error code names and add in the description "For Jazzy and Older". Then for the prefixes, have it be for "Kilted and Newer"

2025-02-11 01:31 UTC, SteveMacenski commented on tutorials/docs/adding_a_nav2_task_server.rst
> +| `Navigator`_ - (nav_to_pose)                      | NONE=0, UNKNOWN=9900  | 9901-9909            |
Mhm, I didn't consider having the different navigators called out, but that does make sense. 

Perhaps we should make 9000-range the navigators, where as nav to pose is 9000-9099; navigate through poses is 9100-9199; and last navigator is 9900-9999

That way each have a 100 elemnt range to use like the other servers. I think only 10 here is too restrictive given how many possible errors could be had at a high level behavior tree (quite possibly the most expressive of the interfaces possible).

2025-02-11 09:19 UTC, ewak commented on tutorials/docs/adding_a_nav2_task_server.rst
> +| `Navigator`_ - (nav_to_pose)                      | NONE=0, UNKNOWN=9900  | 9901-9909            |
Done

2025-02-11 09:19 UTC, ewak commented on configuration/packages/bt-plugins/actions/Spin.rst
> +:error_msg:
Done.  The doc changes have been largely discovered via grep/ag.  Wait never had any error_code so got missed.  Added now.

2025-02-13 01:49 UTC, SteveMacenski commented on configuration/packages/configuring-bt-navigator.rst
> +                  "follow_path"]
```suggestion
  vector<string> ["compute_path_error_code",
                  "follow_path_error_code"]
```

2025-02-13 01:49 UTC, SteveMacenski commented on configuration/packages/configuring-bt-navigator.rst
> +    For Kilted and newer: List of of error code name prefixes to be appended with '_error_code' and searched for during aborted navigator error processing.
```suggestion
    For Kilted and newer: List of of error code name prefixes to be appended with '_error_code' and '_error_msg' and searched for during aborted navigator error processing.
```

2025-02-13 01:49 UTC, SteveMacenski commented on migration/Jazzy.rst
> +The following provides examples of modifications that should be made to behavior tree configurations.
```suggestion
The following provides examples of modifications that should be made to behavior tree configurations to propagate the error messages and codes to the BT navigator result.
```

2025-02-13 01:51 UTC, SteveMacenski approved these changes

2025-03-04 23:31 UTC, merged