Added Vector Pursuit Controller
ros-navigation/docs.nav2.org pull request #596
Opened 2024-10-07 09:52 UTC by exMachina316

# Additions
- Vector Pursuit Controller to the list of supported controllers table
- Tuning guide
- Appropriate links to the github [repo](https://github.com/blackcoffeerobotics/vector_pursuit_controller)

Ref: https://discourse.ros.org/t/vector-pursuit-controller-plugin-for-ros2-navigation/39115/4

2024-10-07 16:41 UTC, SteveMacenski requested changes

2024-10-07 16:41 UTC, SteveMacenski commented on configuration/index.rst
> +   packages/configuring-vector-pursuit-controller.rst
This section is for Nav2 controllers

2024-10-07 16:41 UTC, SteveMacenski commented on plugins/index.rst
> +|  `Vector Pursuit Controller`_  | Black Coffee Robotics| A controller based on the vector | Differential,         |
Please add to the end as has been traditional

2024-10-07 16:41 UTC, SteveMacenski commented on plugins/index.rst
> +|  `Vector Pursuit Controller`_  | Black Coffee Robotics| A controller based on the vector | Differential,         |
I think also this might not format correctly since the BCR touches the trailing `|`

2024-10-07 16:41 UTC, SteveMacenski commented on plugins/index.rst
> +|  `Vector Pursuit Controller`_  | Black Coffee Robotics| A controller based on the vector | Differential,         |
As well with `tracking|` below

2024-10-07 18:15 UTC, exMachina316 commented on plugins/index.rst
> +|  `Vector Pursuit Controller`_  | Black Coffee Robotics| A controller based on the vector | Differential,         |
> Please add to the end as has been traditional

I wasn't aware of the tradition. Duly Noted.

2024-10-07 19:40 UTC, SteveMacenski requested changes
Otherwise, happy to merge!

2024-10-07 19:40 UTC, SteveMacenski commented on setup_guides/algorithm/select_algorithm.rst
> +Next example is the `Vector Pursuit Controller <https://github.com/blackcoffeerobotics/vector_pursuit_controller>`_ . It implements the `Vector Pursuit algorithm <https://apps.dtic.mil/sti/pdfs/ADA46
Again, place this last, but LGTM.

2024-10-07 19:40 UTC, SteveMacenski commented on setup_guides/algorithm/select_algorithm.rst
> +| VP controller   | Differential, Ackermann, Legged                   | High speed path tracking   |
Last :-)

2024-10-07 19:40 UTC, SteveMacenski commented on tuning/index.rst
> +| VP controller  | Differential, Ackermann, Legged                   | High speed path tracking   |
Ditto

2024-10-07 19:40 UTC, SteveMacenski commented on tuning/index.rst
> +Vector Pursuit is another good path tracking solution and just like RPP, is paired with a kinematically feasible planner. It is a bit more advanced than RPP in the sense it also takes path heading in
I would remove "and can handle more complex paths at higher speeds"

2024-10-08 04:26 UTC, exMachina316 commented on tuning/index.rst
> +Vector Pursuit is another good path tracking solution and just like RPP, is paired with a kinematically feasible planner. It is a bit more advanced than RPP in the sense it also takes path heading in
Will this change suffice @SteveMacenski?

Finally, Vector Pursuit is another good path tracking solution and just like RPP, is paired with a kinematically feasible planner. It is a bit more advanced than RPP in the sense it also takes path heading into account. Vector Pursuit can handle complex paths at high speeds, but it is still a simple geometric controller thus requiring low computation resources.

2024-10-08 14:24 UTC, SteveMacenski commented on tuning/index.rst
> +Vector Pursuit is another good path tracking solution and just like RPP, is paired with a kinematically feasible planner. It is a bit more advanced than RPP in the sense it also takes path heading in
Yeah that looks good!

2024-10-08 14:30 UTC, exMachina316 commented on tuning/index.rst
> +Vector Pursuit is another good path tracking solution and just like RPP, is paired with a kinematically feasible planner. It is a bit more advanced than RPP in the sense it also takes path heading in
Yes I understand how it could have been interpreted in that sense despite it not being the intention. I'll push the changes then.

2024-10-08 15:57 UTC, merged