Add missing params for loopback_sim
ros-navigation/docs.nav2.org pull request #600
Opened 2024-10-18 10:12 UTC by adivardi

2024-10-21 08:57 UTC, SteveMacenski requested changes
Otherwise, happy to merge

2024-10-21 08:57 UTC, SteveMacenski commented on configuration/packages/configuring-loopback-sim.rst
> +  string         `false`
Remove the "`" to be inline with other param tables. 

Also, for rst format, you would have had to use 2x of those to get it to consider a code block. 1x is in italics

2024-10-28 09:32 UTC, adivardi commented on configuration/packages/configuring-loopback-sim.rst
> +  string         `false`
fixed both issues

2024-11-04 18:09 UTC, SteveMacenski approved these changes
Sorry for the delay, we had ROSCon, ROS-I, and then I took a short vacation while in Europe. I'm getting back to work this morning :-)

2024-11-04 18:10 UTC, merged