Add note on multirobot refactor to migration guide
ros-navigation/docs.nav2.org pull request #609
Opened 2024-11-20 04:45 UTC by luca-della-vedova

Add migration for PR https://github.com/ros-navigation/navigation2/pull/4715

2024-11-20 19:21 UTC, SteveMacenski requested changes

2024-11-20 19:21 UTC, SteveMacenski commented on migration/Jazzy.rst
> +*******************************************************
The `***`'s annoyingly need to match the length of the title in rst in order to render properly. 

Also, for those sensor data topics that were updated with the namespacing changes, please add a note like the inline code example you provided in the obstacle layer for how to configure it (and recommend `/` prefix if you dont want to deal with namespaces). That way, its clearly up-front for users reading the docs the expected behavior they'll see without guessing and checking

2024-11-21 02:45 UTC, luca-della-vedova commented on migration/Jazzy.rst
> +*******************************************************
https://github.com/ros-navigation/docs.nav2.org/pull/609/commits/03da77955501e786e1734cd8c80626dfe5727068

2024-11-21 19:18 UTC, SteveMacenski commented on migration/Jazzy.rst
> +*******************************************************
Please also add that note in the `topic` configuration guide entries i.e. 
- https://docs.nav2.org/configuration/packages/costmap-plugins/obstacle.html
- https://docs.nav2.org/configuration/packages/costmap-plugins/voxel.html
- https://docs.nav2.org/configuration/packages/costmap-plugins/range.html
- https://docs.nav2.org/configuration/packages/costmap-plugins/static.html

I want this to be really loud and clear

2024-11-22 02:34 UTC, luca-della-vedova commented on migration/Jazzy.rst
> +*******************************************************
https://github.com/ros-navigation/docs.nav2.org/pull/609/commits/c42eb570e33d608e7d3154c96de94e4f19a2300a

2024-11-22 20:14 UTC, SteveMacenski commented on configuration/packages/costmap-plugins/obstacle.rst
> +  Relative topics will be relative to the node's parent namespace.
These don't render properly: https://output.circle-artifacts.com/output/job/190ba9cc-e4b2-4590-b0e4-838801870a4f/artifacts/0/html/configuration/packages/costmap-plugins/obstacle.html

I think that's fixed by adding an empty line before the first bullet (after the line ending with `:` to separate it)

2024-11-22 23:59 UTC, SteveMacenski commented
One more thing and this should be done https://docs.nav2.org/tuning/index.html --> remove the `use_namespace` parameter description if we're removing it

2024-11-25 20:00 UTC, SteveMacenski approved these changes

2024-11-26 19:58 UTC, SteveMacenski commented
I fixed some formatting for you, LGTM

2024-11-27 02:55 UTC, luca-della-vedova commented
It shows that I only wrote markdown in my life :sweat_smile:, noticed that the highlighting of snippets wasn't working because it's supposed to be double backtick so fixed that in https://github.com/ros-navigation/docs.nav2.org/pull/609/commits/3cc1e2e5cbde230740064556c9a450d0d6238a69

2024-11-27 18:13 UTC, SteveMacenski requested changes

2024-11-27 18:13 UTC, SteveMacenski commented on configuration/packages/costmap-plugins/range.rst
> +  Relative topics will be relative to the node's parent namespace.
Missed the entry for `map_topic` now  :wink: 

Sorry to be a stickler about docs, I know its frustrating :(

2024-11-27 18:13 UTC, SteveMacenski commented
Otherwise, I can merge

2024-11-28 09:23 UTC, luca-della-vedova commented on configuration/packages/costmap-plugins/range.rst
> +  Relative topics will be relative to the node's parent namespace.
Apologies not sure I follow, I thought `map_topic` is only a parameter in `static_layer`? Why is this comment on `range_sensor_layer`?

```
lucadv@noble:~/ionic_ws/src/nav2/navigation2/nav2_costmap_2d/plugins$ grep -r . -e map_topic
./static_layer.cpp:    map_topic_.c_str(),
./static_layer.cpp:    map_topic_, map_qos,
./static_layer.cpp:      map_topic_ + "_updates",
./static_layer.cpp:  declareParameter("map_topic", rclcpp::ParameterValue("map"));
./static_layer.cpp:  node->get_parameter(name_ + "." + "map_topic", map_topic_);
./static_layer.cpp:  map_topic_ = joinWithParentNamespace(map_topic_);
./static_layer.cpp:      param_name == name_ + "." + "map_topic" ||
```

2024-12-02 00:55 UTC, SteveMacenski commented on configuration/packages/costmap-plugins/range.rst
> +  Relative topics will be relative to the node's parent namespace.
I mean that i wanted you to add this block wrt clarification on the relative topic namespaces into the static layer's configuration guide for the `map_topic` now that it has the same behavior profile as `topic` for range / obstacle / voxel layers

2024-12-03 01:22 UTC, luca-della-vedova commented on configuration/packages/costmap-plugins/range.rst
> +  Relative topics will be relative to the node's parent namespace.
Is https://github.com/ros-navigation/docs.nav2.org/blob/02509d147419e3d01b7a8a14d704857f2452c57a/configuration/packages/costmap-plugins/static.rst?plain=1#L65-L82 OK?

2024-12-03 01:48 UTC, SteveMacenski commented on configuration/packages/costmap-plugins/range.rst
> +  Relative topics will be relative to the node's parent namespace.
I think `Map topic to subscribe to. If left empty the map topic will default to the global `map_topic` parameter in `costmap_2d_ros`.` should be removed. The default should also be updated to `"map"` from the change as well. Otherwise, LGTM

2024-12-03 01:55 UTC, SteveMacenski approved these changes

2024-12-03 01:57 UTC, merged