Plugin container layer docs
ros-navigation/docs.nav2.org pull request #615
Opened 2024-12-03 22:57 UTC by alexanderjyuen

Added documentation for plugin container layer

2024-12-04 01:52 UTC, SteveMacenski requested changes
Just add to the migration guide that "hey we have a new layer, here's why its nice, check out the configuration guide" with a link. Its a promotion :-)

2024-12-04 01:52 UTC, SteveMacenski commented on configuration/packages/costmap-plugins/plugin_container.rst
> +
At the end here is where I'd recommend having the example YAML configuration. You could also get away without doing a separate tutorial if you included an image of that example YAML with 2x of these containers surrounding 2x dfiferent layers with different inflations to show case it "working" to prove the point visually 

This is also missing a parameter for the plugin types (the `nav2_util` plugin loader has one internal, its `<plugin_name>.plugins`)

2024-12-04 01:52 UTC, SteveMacenski commented on plugins/index.rst
> +| `Plugin Container Layer`_      |  Alexander Yuen        | Combines the different layers    |
Maybe reword this to be a little more clear :upside_down_face:

2024-12-04 01:52 UTC, SteveMacenski commented on tuning/index.rst
> +- ``PluginContainerLayer``: Combines the layers above to allow for different submaps to exist in the map. This would allow applying different denoise layers or inflation layers to different obstacle
Ditto

2024-12-05 21:19 UTC, alexanderjyuen commented on configuration/packages/costmap-plugins/plugin_container.rst
> +
Is this necessary? I am presently getting the `plugin_types` in the [following way](https://github.com/alexanderjyuen/navigation2/blob/feature-plugin-container-layer/nav2_costmap_2d/plugins/plugin_container_layer.cpp#L69)

2024-12-11 19:12 UTC, alexanderjyuen commented
Example image updated

2024-12-11 19:12 UTC, alexanderjyuen commented on configuration/packages/costmap-plugins/plugin_container.rst
> +
Added to the migration guide

2024-12-11 19:23 UTC, alexanderjyuen commented on configuration/packages/costmap-plugins/plugin_container.rst
> +          plugin: "nav2_costmap_2d::StaticLayer"
@SteveMacenski if the plugin type is explicitly defined in each constituent layer, do I still need an parameter for `plugin_types`

2024-12-11 19:48 UTC, SteveMacenski commented on configuration/packages/costmap-plugins/plugin_container.rst
> +          plugin: "nav2_costmap_2d::StaticLayer"
Its not defined in the layer as I mentioned. Your util that loads the plugin (https://github.com/ros-navigation/navigation2/blob/684a4d037241674550b756c5014711fa6c13e35e/nav2_util/include/nav2_util/node_utils.hpp#L136) itself defines that `.plugin` parameter so it can read the string of the plugin class in order to load it. That is a parameter that you have actually added by using `get_plugin_type_param`

2024-12-11 19:50 UTC, SteveMacenski commented
Otherwise, with that missing parameter + fixing DCO, I can merge this and the PR!

2024-12-13 01:09 UTC, SteveMacenski approved these changes

2024-12-13 01:10 UTC, merged