Update First-Time Robot Setup Guide for Modern Gazebo
ros-navigation/docs.nav2.org pull request #618
Opened 2024-12-10 13:37 UTC by Amronos

Fixes #608.

- [x] Update setup_odom.rst
- [ ] Update setup_sensors.rst

2024-12-10 23:43 UTC, SteveMacenski reviewed
First of all, a huge, huge thank you for taking this on, it really helps alot to get some support in updating documentation :-) 

I'm wondering if we should possibly create new pages for the odometry, sensors (in addition to the SDF we've already discussed) and leave the current pages alone. That would let you start fresh (which would probably make this easier honestly than trying to shoe horn the changes in) and also let us on the Index page https://docs.nav2.org/setup_guides/index.html allow people to choose their adventure for GZ Classic or Modern GZ if they're still on Humble. Unfortunately Humble is supported until mid-2025, so there will still be alot of GZ Classic users around for awhile. 

Basically what I'm thinking is to have 2 parallel table contents, one for GZ and another for GZ Classic. They'd both share the Transformations and URDF tutorials, but the Odometry, Sensors, and SDF would change by simulator -- and then the Footprint / Plugins would again be the same. That would also give us a recipe to work with for adding support for new simulators in the future

Then once that passes, we can just delete those changes to complete the migration. What do you think? I think that would make your life easier by being able to have more control on the flow of the guide page and code blocks instead of trying to make a 1:1 analog.

2024-12-10 23:43 UTC, SteveMacenski commented on setup_guides/odom/setup_odom.rst
> +Note that you may have described ``sam_bot`` using URDF. However, Gazebo uses `Simulation Description Format (SDF) <http://sdformat.org/>`_ to describe a robot in its simulated environment. Fortunate
I believe we're separating the SDF files now. I think the SDF tutorial should be before this one, so they should have one already (with basic frames?) that we're modifying to setup the odometry / diff drive controller

2024-12-11 11:08 UTC, Amronos commented
> First of all, a huge, huge thank you for taking this on, it really helps alot to get some support in updating documentation :-)

You are welcome! Thanks a lot for appreciating the effort.

> I'm wondering if we should possibly create new pages for the odometry, sensors (in addition to the SDF we've already discussed) and leave the current pages alone. That would let you start fresh (which would probably make this easier honestly than trying to shoe horn the changes in) and also let us on the Index page [docs.nav2.org/setup_guides/index.html](https://docs.nav2.org/setup_guides/index.html) allow people to choose their adventure for GZ Classic or Modern GZ if they're still on Humble. Unfortunately Humble is supported until mid-2025, so there will still be alot of GZ Classic users around for awhile.
> 
> Basically what I'm thinking is to have 2 parallel table contents, one for GZ and another for GZ Classic. They'd both share the Transformations and URDF tutorials, but the Odometry, Sensors, and SDF would change by simulator -- and then the Footprint / Plugins would again be the same. That would also give us a recipe to work with for adding support for new simulators in the future
> 
> Then once that passes, we can just delete those changes to complete the migration. What do you think? I think that would make your life easier by being able to have more control on the flow of the guide page and code blocks instead of trying to make a 1:1 analog.

Those ideas do sound good to me. I'm not sure what you mean by "2 parallel table contents." Could you go into a bit more detail about that/how to implement it?

2024-12-11 11:15 UTC, Amronos commented on setup_guides/odom/setup_odom.rst
> +Note that you may have described ``sam_bot`` using URDF. However, Gazebo uses `Simulation Description Format (SDF) <http://sdformat.org/>`_ to describe a robot in its simulated environment. Fortunate
This is something defined in line 90 of the old tutorial, which I slightly updated. I think since we have/will be having a URDF and SDF tutorial now, this is something that may cause confusion so I will remove it.

2024-12-11 19:06 UTC, SteveMacenski commented
In the index page, we have a section called "Table of Contents" where we list those guide pages. Instead, we could have 2 separate sections, one for GZ Modern and another for GZ Classic where we link the appropriate versions of the pages. For some, they'll be the same page (URDF, Footprint), but for others they'll change (the ones you're working on). 

that would give us the tutorials for both up simultaneously and give you more free reign on the Modern GZ pages to break from the existing where things change more easily

2025-01-04 07:00 UTC, Amronos commented
@SteveMacenski, I'm sorry for the delay on this! I will try my best to get this completed in a couple of days.
I tried my best to implement what you suggested for the index page. Do give feedback if it isn't how you expected it to be (I don't think it is).

2025-01-07 22:37 UTC, SteveMacenski commented
Hey no worries at all - the holidays are for relaxing afterall :-)

2025-01-07 23:03 UTC, SteveMacenski requested changes
Nice thinking in breaking out the robot localization page for both to share :-)

2025-01-07 23:03 UTC, SteveMacenski commented on setup_guides/odom/setup_odom_gz.rst
> +Finally, create a file named ``bridge_config.yaml`` in the ``config`` directory of your package and add the following line to it to define what topics we want to bridge between ROS and Gazebo:
I think we should have a subsection after the _Adding Gazebo Plugins to a URDF/SDF_  section called _Creating Gazebo Bridge_ which does this (and adds a little explanation about the bridge). For example:
- There is a bridge :laughing: 
- It translates GZ topics to ROS topics
- We have to launch the bridge with a configuration about what topics to translate and what their ROS types are 

So I think this should be moved before _Launch and Build Files_ so this file is setup and ready by the time they go to actually modifying launch files. I think that's important because having the filepath to this config file is part of the launch modifications

2025-01-07 23:03 UTC, SteveMacenski commented on setup_guides/odom/setup_odom_gz.rst
> +      config_file=bridge_config_path,
I don't think this path is defined yet in the instructions

2025-01-08 02:18 UTC, Amronos commented
About the SDF and URDF things:
What I am trying to do here is to allow the readers to use either the URDF or SDF, whichever they are more comfortable with using / like more as it is possible to not use both the description formats and just use one instead. :-)
Of course if they want they could do what has been done in the nav2_min_tb3_sim package instead of using a single description format.

2025-01-08 02:58 UTC, SteveMacenski commented
Ah I see, I think we should have the instructions be best practices: URDF for robot description, SDF for simulation, and we help them setup both. I don't think its wise to give folks too many options in first time setup (since they're new to all this and can't make a knowledgeable trade off yet), so I think its best to go with the best practices only.

2025-01-08 12:41 UTC, Amronos commented on setup_guides/index.rst
> +- Introduce TF2 and setup your robot URDF or SDF
I still think this should be URDF or SDF, as in most use cases, both are not needed. I will add a note in the tutorials for URDF & SDF, that the other is an option and to use SDF if the reader is going to make a Gazebo simulation.

2025-01-08 12:48 UTC, Amronos commented on setup_guides/odom/setup_odom_gz.rst
> +    <link name="front_caster">
The part where I set the ``<mu>`` tags hasn't been done in that section. Also, the reason I am including this here is that I think something related to this changed from Gazebo Classic to Modern Gazebo as it isn't present in the older tutorials and I think that various SDF related changes have also happened.
Will move it to setup_urdf and setup_sdf if this is not the case.

2025-01-08 13:56 UTC, Amronos commented on setup_guides/index.rst
> +- Introduce TF2 and setup your robot URDF or SDF
> I will add a note in the tutorials for URDF & SDF, that the other is an option and to use SDF if the reader is going to make a Gazebo simulation.

Done in [4209601](https://github.com/ros-navigation/docs.nav2.org/pull/618/commits/4209601c369b2d292a7dd8507cf9e4f25dc5bac5).

2025-01-08 13:59 UTC, Amronos commented on setup_guides/index.rst
>     transformation/setup_transforms.rst
Thanks! Did it in [2f92964](https://github.com/ros-navigation/docs.nav2.org/pull/618/commits/2f929644a5a334709b1bbfea187c43eb139d4e0f), had to use a bit of chatgpt too. :-)

2025-01-09 00:20 UTC, SteveMacenski commented on setup_guides/index.rst
>     transformation/setup_transforms.rst
So I see the 2 sections, but none of the actual links on it https://output.circle-artifacts.com/output/job/95f5e86b-5415-4fcd-8b17-ec6cdff44bb5/artifacts/0/html/setup_guides/index.html -- did you test this locally?

2025-01-09 00:22 UTC, SteveMacenski commented on setup_guides/index.rst
> +- Introduce TF2 and setup your robot URDF or SDF
@Amronos I think for new Gazebo, they really are pushing you down the road of using SDFs and separate URDFs. That has been best practices in Gazebo Classic for awhile, but old habits die hard.

I think for the purposes of this tutorial, we should only propose this as URDF **and** SDF. URDF is the basic robot frames and descriptions. SDF is the gazebo plugins and simulation items

2025-01-18 07:26 UTC, Amronos commented on setup_guides/odom/setup_odom_gz.rst
> +      config_file=bridge_config_path,
Done in [e60812d](https://github.com/ros-navigation/docs.nav2.org/pull/618/commits/e60812d6d14a0514c37fa8ed901d44bbf0af737b)

2025-01-18 07:27 UTC, Amronos commented on setup_guides/odom/setup_odom_gz.rst
> +Finally, create a file named ``bridge_config.yaml`` in the ``config`` directory of your package and add the following line to it to define what topics we want to bridge between ROS and Gazebo:
Done in [e60812d](https://github.com/ros-navigation/docs.nav2.org/pull/618/commits/e60812d6d14a0514c37fa8ed901d44bbf0af737b).

2025-01-18 07:27 UTC, Amronos commented on setup_guides/odom/setup_odom_gz.rst
> +  <gazebo reference="front_caster">
Done in [e60812d](https://github.com/ros-navigation/docs.nav2.org/pull/618/commits/e60812d6d14a0514c37fa8ed901d44bbf0af737b).

2025-01-18 07:29 UTC, Amronos commented on setup_guides/odom/setup_odom_gz_classic.rst
>  In this guide, we will be looking at how to integrate our robot's odometry system with Nav2.
Done in [e60812d](https://github.com/ros-navigation/docs.nav2.org/pull/618/commits/e60812d6d14a0514c37fa8ed901d44bbf0af737b).

2025-01-18 07:29 UTC, Amronos commented on setup_guides/index.rst
>     transformation/setup_transforms.rst
Fixed in [e60812d](https://github.com/ros-navigation/docs.nav2.org/pull/618/commits/e60812d6d14a0514c37fa8ed901d44bbf0af737b).

2025-01-18 07:38 UTC, Amronos commented on setup_guides/index.rst
> +- Introduce TF2 and setup your robot URDF or SDF
But I don't really see the use of making both a URDF and an SDF since both the description formats can contain the simulation items and the basic robot descriptions fully.

I do understand the want to separate it into SDF for simulation items and URDF for basic robot descriptions, but I don't think it's possible to use both the description formats at the same time with them each having a part of the robot description (instead of the full thing).
If one decides to make them both, then in the end you can only choose one of them for the launch file. This means the other description just exists without much use.

2025-01-18 07:38 UTC, Amronos commented on setup_guides/odom/setup_odom_gz.rst
> +
Done in [e60812d](https://github.com/ros-navigation/docs.nav2.org/pull/618/commits/e60812d6d14a0514c37fa8ed901d44bbf0af737b).

2025-01-21 23:27 UTC, SteveMacenski commented on setup_guides/sdf/setup_sdf.rst
> +.. note:: You can also setup a URDF description, see :ref:`urdf_handson`. It is recommended to setup a SDF instead of URDF if you are going to be using Gazebo. There is no need to setup both URDF and
This not is not true, you do need a URDF file for the robot state publisher to use without a simulator. It is required to have a URDF for a robot for any Nav2 use -- then separately an SDF (or SDF terms embedded into the URDF) for use in simulation.

2025-01-21 23:27 UTC, SteveMacenski commented on setup_guides/sdf/setup_sdf.rst
> +.. note:: You can also setup a URDF description, see :ref:`urdf_handson`. It is recommended to setup a SDF instead of URDF if you are going to be using Gazebo. There is no need to setup both URDF and
But I would just delete this entire note. I think we're trying to guide people down best practices and we should have the SDF file. If people want to embed into their URDF, then they can, but I don't think we should be bringing it up

2025-01-21 23:27 UTC, SteveMacenski commented on setup_guides/sdf/setup_sdf.rst
> +For this guide, we will be creating the SDF (Simulation Description Format) file for a simple differential drive robot to give you hands-on experience on working with SDF. We will also setup the robo
```suggestion
For this guide, we will be creating the SDF (Simulation Description Format) file for a simple differential drive robot to give you hands-on experience on building an SDF file for Gazebo simulation. We will also setup the robot state publisher and visualize our model in RVIZ. Lastly, we will be adding some kinematic properties to our robot SDF to prepare it for simulation purposes. These steps are necessary to represent all the sensor, hardware, and robot transforms of your robot for use in navigation.
```

2025-01-21 23:27 UTC, SteveMacenski commented on setup_guides/sdf/setup_sdf.rst
> +As discussed in the previous tutorial, one of the requirements for Navigation2 is the transformation from  ``base_link`` to the various sensors and reference frames. This transformation tree can rang
Change 2x in the text of "Navigation2" to "Nav2"

2025-01-21 23:27 UTC, SteveMacenski commented on setup_guides/sdf/setup_sdf.rst
> +The Robot State Publisher is a package of ROS 2 that interacts with the tf2 package to publish all of the necessary transforms that can be directly inferred from the geometry and structure of the rob
This is not true, that is the role of the URDF. The SDF is for simulation. The URDF is what creates the static transform tree that the robot state publisher uses.

This section looks like it is from the URDF tutorial and needs to be updated for SDF :-)

2025-01-21 23:27 UTC, SteveMacenski commented on setup_guides/sdf/setup_sdf.rst
> +  sudo apt install ros-<ros2-distro>-sdformat_urdf
```suggestion
  sudo apt install ros-<ros2-distro>-sdformat-urdf
```

I'm guessing this is what you mean :wink:

2025-01-21 23:27 UTC, SteveMacenski commented on setup_guides/sdf/setup_sdf.rst
> +  ros2 pkg create --build-type ament_cmake sam_bot_description
Shouldn't this exist from the URDF tutorial?

2025-01-21 23:27 UTC, SteveMacenski commented on setup_guides/sdf/setup_sdf.rst
> +Now that we have our project workspace set up, let's dive straight into writing the SDF. Below is an image of the robot we will be trying to build.
I'm going to stop here on this tutorial - this is a copy-ish of the URDF tutorial. I think this needs to be re-written as an SDF tutorial. The user has a URDF from the previous tutorial already complete. This should be about writing the SDF file to compliment the URDF for use in GZ

2025-01-21 23:27 UTC, SteveMacenski commented on setup_guides/index.rst
> +- Introduce TF2 and setup your robot URDF or SDF
> But I don't really see the use of making both a URDF and an SDF since both the description formats can contain the simulation items and the basic robot descriptions fully.

I think they don't have to. If you look at the nav2_minimal_tb3_sim package, we have completely decoupled URDF and SDF:
- https://github.com/ros-navigation/nav2_minimal_turtlebot_simulation/blob/main/nav2_minimal_tb3_sim/urdf/turtlebot3_waffle.urdf
- https://github.com/ros-navigation/nav2_minimal_turtlebot_simulation/blob/main/nav2_minimal_tb3_sim/urdf/gz_waffle.sdf.xacro
- https://github.com/ros-navigation/nav2_minimal_turtlebot_simulation/blob/main/nav2_minimal_tb3_sim/configs/turtlebot3_waffle_bridge.yaml
- https://github.com/ros-navigation/nav2_minimal_turtlebot_simulation/blob/main/nav2_minimal_tb3_sim/launch/spawn_tb3.launch.py

This is already shown and this was setup by the Gazebo maintainers themselves, so this is an example of best practices, and you can see how it can be launched / bridged as well. There are no GZ/Gazebo terms in the URDF

2025-01-21 23:46 UTC, SteveMacenski requested changes
Thanks again! I did another run through and it looks like the only remaining thing is getting on the same page about URDF and SDF. Let me explain what I'm thinking

* URDF is the file used by the robot state publisher to setup the static frames and visualize the robot in rviz. This is used regardless of simulator, if we're using a simulator, or a physical robot. This must always be present.
* SDF is a specific file for Gazebo / GZ for describing the simulator environment or model - and wouldn't be used if using something like Isaac Sim or Open3D Engine
* We can setup URDFs that are SDF and Gazebo-free (see https://github.com/ros-navigation/docs.nav2.org/pull/618#discussion_r1924488417), so we should as best practices from the GZ maintainers. We should also be recommending that to users. If they happen to do something else, that's on them, but this is the habit we should be steering people down -- both so that they can swap simulators later easily and so that if Gazebo stops supporting implicit URDF to SDF conversions, we don't need to update everything
* So with that in mind, the tutorial has a URDF section that sets up the basic static frames. We should build on that in the SDF tutorial, not replace it. We should have the SDF setup for what the SDF needs as the base-file going into the Odom/Sensor/other tutorials (installing SDF, if needed; creating the file next to the URDF; copying over whatever from the URDF is minimally required)
* In the later tutorial steps, we should have the frames added to the URDF and the simulator items added into the SDF. But we should be having both, not expressing things as optional or having an option to do it one of two ways

2025-01-21 23:46 UTC, SteveMacenski commented on setup_guides/urdf/setup_urdf.rst
> +.. note:: You can also setup a SDF description if using Gazebo (not Gazebo Classic), see :ref:`sdf_handson`. It is recommended to setup a SDF instead of URDF if you are going to be using Gazebo. Ther
Remove note, see https://github.com/ros-navigation/docs.nav2.org/pull/618#discussion_r1924488417. SDF and URDF are not interchangable and serve different purposes.

2025-01-21 23:46 UTC, SteveMacenski commented on setup_guides/odom/setup_odom_gz.rst
> +If using SDF add the following lines before the ``</model>`` line:
See ^, we should only be recommending instructions with the SDF

2025-01-21 23:46 UTC, SteveMacenski commented on setup_guides/odom/setup_odom_gz.rst
> +If using SDF, add the following lines after the ``</link>`` tag of the IMU sensor:
Ditto: only recommend use of SDF

2025-01-21 23:46 UTC, SteveMacenski commented on setup_guides/odom/setup_odom_gz.rst
> +If using SDF, modify the caster link as shown below:
Ditto: only SDF.

2025-01-21 23:46 UTC, SteveMacenski commented on setup_guides/odom/setup_odom_gz.rst
> +Making a Gazebo world
I might recommend clipping this section and just putting in a setnence in the Build, Run, and Verification section that there's an empty world file in the navigation2_tutorials package that we'll be using (with a link) and copy it over. I don't think we need to put it inline since its a supporting piece

2025-01-21 23:46 UTC, SteveMacenski commented on setup_guides/sensors/setup_sensors_gz.rst
> +Let us first add a lidar sensor to ``sam_bot``. If using URDF paste the following lines before the ``</robot>`` tag.
Ditto on SDF from other comments

2025-01-21 23:46 UTC, SteveMacenski commented on setup_guides/sensors/setup_sensors_gz.rst
> +
Its missing the explanation line. From GZ Classic (should adopt for new Gazebo, but same gist):

> In the code snippet above, we create a lidar_link which will be referenced by the gazebo_ros_ray_sensor plugin as the location to attach our sensor. We also set values to the simulated lidar’s scan and range properties. Lastly, we set the /scan as the topic to which it will publish the sensor_msgs/LaserScan messages.

2025-01-21 23:46 UTC, SteveMacenski commented on setup_guides/sensors/setup_sensors_gz.rst
> +
Missing the same description line:

> Similar to the lidar sensor, we create camera_link which will be referenced by the gazebo_ros_camera plugin as the sensor attachment location. We also create a camera_depth_frame that is attached to the camera_link and will be set as the <frame_name> of the depth camera plugin. We also configure the plugin such that it will publish sensor_msgs/Image and sensor_msgs/PointCloud2 messages to /depth_camera/image_raw and /depth_camera/points topics respectively. Lastly, we also set up other basic configuration properties for our depth camera.

2025-01-21 23:46 UTC, SteveMacenski commented on setup_guides/sensors/setup_sensors_gz.rst
> +
This seems to be missing the `Launch and Build Files` section from the GZ classic version

2025-01-21 23:51 UTC, SteveMacenski commented
This is overall really good! Thanks so much for your efforts here so far :smile:

2025-01-22 11:13 UTC, Amronos commented
@SteveMacenski thanks a lot for the reviews and sorry for being a bit difficult with the URDF and SDF things. I get your point now. I think this reasoning should also be available to the readers so is it ok if I add the following note in the URDF tutorial and SDF tutorials.

"Note that you will also be setting up a SDF for simulation in Gazebo in the next tutorials, you don't need to and shouldn't make it if you are not going to use Gazebo. If you are writing a SDF and think you will not be using any other simulator except Gazebo there isn't really a need to write the URDF but you should still write it in case you encounter a ROS package that requires it or you switch simulators."

2025-01-22 12:06 UTC, Amronos commented on setup_guides/sensors/setup_sensors_gz.rst
> +
I didn't have anything to put in it as it all gets discussed in setup_odom_gz, the only thing for this tutorial was mostly expanding the bridge and updating the description files.

2025-01-22 12:10 UTC, Amronos commented on setup_guides/odom/setup_odom_gz.rst
> +Making a Gazebo world
I would like to guide the reader a bit better as we also make a small change in the CMakeLists.txt.

2025-01-22 12:11 UTC, Amronos commented on setup_guides/sdf/setup_sdf.rst
> +  sudo apt install ros-<ros2-distro>-sdformat_urdf
Thanks!

2025-01-22 21:26 UTC, SteveMacenski commented on setup_guides/odom/setup_odom_gz.rst
> +Making a Gazebo world
OK - I think this could be [a dropdown](https://sphinx-design.readthedocs.io/en/latest/dropdowns.html) then so that it can be opened if someone wants to look at it (otherwise point to a link to it).

2025-01-22 21:32 UTC, SteveMacenski commented on setup_guides/sensors/setup_sensors_gz.rst
> +
I think the Odom one just sets up an empty world, the sensors one adds in a few objects to just show that the sensor data is being properly populated using the plugins to verify that it works https://docs.nav2.org/setup_guides/sensors/setup_sensors.html#launch-and-build-files

![image](https://github.com/user-attachments/assets/e2eb842a-3164-49b1-a9e3-ae3d9cb907c6)

I don't think the cube/sphere are setup in the Odom tutorial, that's added here, no?

If we do have the world file in the Odom tutorial include the cube/sphere already, that works!

2025-01-22 21:32 UTC, SteveMacenski commented on setup_guides/sensors/setup_sensors_gz.rst
> +
Ah, I see taht the odom one does, OK! Ignore this then. I might just mention in the Odom tutorial that the world file contains a few objects for later tutorials on sensors.

2025-01-22 21:42 UTC, SteveMacenski commented
I'd rewrite a little to: 

"Note that you will also be setting up a SDF for simulation in Gazebo in the next tutorials. URDF is used to set up the robot frames and describe the robot's structure. SDF is a specific file for simulators, like Gazebo, that describes the simulator environment, model (including its frames and Gazebo-specific information), and appropriate plugins. The SDF that we will make is for Gazebo, but could be replaced with an appropriate SDF or other format file for Open3D Engine or Isaac Sim."   

Its a little more concise - and you actually can use SDF with other simulators, but most of the SDF we're setting up is with Gazebo sensor and odometry plugins, which are obviously going to be different from other simulators since they have their own plugins or capabilities. So I think this is important to reword for that distinction. 

> Also, I think the SDF tutorial should remain as it is (if you agree with the above note) with a message that some parts of it will seem redundant if the URDF tutorial has been followed. P.S. I would like if you had a look at this.

Isn't this still saying do 'this' or 'that' for SDF vs URDF? I think we want to steer down a single direction still

2025-01-23 01:53 UTC, Amronos commented
Ok, thanks! Will make the necessary changes needed then in all the tutorials.

2025-01-25 05:02 UTC, Amronos commented on setup_guides/odom/setup_odom_gz.rst
> +Making a Gazebo world
I tried to do this but it didn't work and gave the below error.

```shell
ERROR: Unknown directive type "dropdown".

.. dropdown:: Making a Gazebo world
```

2025-01-25 05:03 UTC, Amronos commented on setup_guides/sensors/setup_sensors_gz.rst
> +
Done in [aa61c35](https://github.com/ros-navigation/docs.nav2.org/pull/618/commits/aa61c35af0cbbf034aff4c5d1eccf7923ceba553).

2025-01-25 05:04 UTC, Amronos commented on setup_guides/sensors/setup_sensors_gz.rst
> +
Done in [aa61c35](https://github.com/ros-navigation/docs.nav2.org/pull/618/commits/aa61c35af0cbbf034aff4c5d1eccf7923ceba553).

2025-01-25 05:04 UTC, Amronos commented on setup_guides/sensors/setup_sensors_gz.rst
> +Let us first add a lidar sensor to ``sam_bot``. If using URDF paste the following lines before the ``</robot>`` tag.
Done in [aa61c35](https://github.com/ros-navigation/docs.nav2.org/pull/618/commits/aa61c35af0cbbf034aff4c5d1eccf7923ceba553).

2025-01-25 05:04 UTC, Amronos commented on setup_guides/odom/setup_odom_gz.rst
> +If using SDF, modify the caster link as shown below:
Done in [aa61c35](https://github.com/ros-navigation/docs.nav2.org/pull/618/commits/aa61c35af0cbbf034aff4c5d1eccf7923ceba553).

2025-01-25 05:04 UTC, Amronos commented on setup_guides/odom/setup_odom_gz.rst
> +If using SDF, add the following lines after the ``</link>`` tag of the IMU sensor:
Done in [aa61c35](https://github.com/ros-navigation/docs.nav2.org/pull/618/commits/aa61c35af0cbbf034aff4c5d1eccf7923ceba553).

2025-01-25 05:04 UTC, Amronos commented on setup_guides/urdf/setup_urdf.rst
> +.. note:: You can also setup a SDF description if using Gazebo (not Gazebo Classic), see :ref:`sdf_handson`. It is recommended to setup a SDF instead of URDF if you are going to be using Gazebo. Ther
Done in [aa61c35](https://github.com/ros-navigation/docs.nav2.org/pull/618/commits/aa61c35af0cbbf034aff4c5d1eccf7923ceba553).

2025-01-25 05:04 UTC, Amronos commented on setup_guides/sdf/setup_sdf.rst
> +Now that we have our project workspace set up, let's dive straight into writing the SDF. Below is an image of the robot we will be trying to build.
Done in [aa61c35](https://github.com/ros-navigation/docs.nav2.org/pull/618/commits/aa61c35af0cbbf034aff4c5d1eccf7923ceba553).

2025-01-25 05:04 UTC, Amronos commented on setup_guides/sdf/setup_sdf.rst
> +  ros2 pkg create --build-type ament_cmake sam_bot_description
Done in [aa61c35](https://github.com/ros-navigation/docs.nav2.org/pull/618/commits/aa61c35af0cbbf034aff4c5d1eccf7923ceba553).

2025-01-25 05:04 UTC, Amronos commented on setup_guides/sdf/setup_sdf.rst
> +The Robot State Publisher is a package of ROS 2 that interacts with the tf2 package to publish all of the necessary transforms that can be directly inferred from the geometry and structure of the rob
Done in [aa61c35](https://github.com/ros-navigation/docs.nav2.org/pull/618/commits/aa61c35af0cbbf034aff4c5d1eccf7923ceba553).

2025-01-25 05:04 UTC, Amronos commented on setup_guides/sdf/setup_sdf.rst
> +As discussed in the previous tutorial, one of the requirements for Navigation2 is the transformation from  ``base_link`` to the various sensors and reference frames. This transformation tree can rang
Done in [aa61c35](https://github.com/ros-navigation/docs.nav2.org/pull/618/commits/aa61c35af0cbbf034aff4c5d1eccf7923ceba553).

2025-01-25 05:04 UTC, Amronos commented on setup_guides/sdf/setup_sdf.rst
> +.. note:: You can also setup a URDF description, see :ref:`urdf_handson`. It is recommended to setup a SDF instead of URDF if you are going to be using Gazebo. There is no need to setup both URDF and
Done in [aa61c35](https://github.com/ros-navigation/docs.nav2.org/pull/618/commits/aa61c35af0cbbf034aff4c5d1eccf7923ceba553).

2025-01-28 00:02 UTC, SteveMacenski commented on setup_guides/odom/setup_odom_gz.rst
> +Making a Gazebo world
@Amronos I think it has to be 

```
.. dropdown:: 

  Making a Gazebo world
```

2025-01-28 00:06 UTC, SteveMacenski commented on setup_guides/odom/setup_odom_gz.rst
> +Making a Gazebo world
If that doesn't work, see: https://github.com/ros-navigation/docs.nav2.org/blob/master/development_guides/build_docs/index.rst

It uses `.. rst-class:: content-collapse` and sections to create collapsing sections in https://docs.nav2.org/development_guides/build_docs/index.html#install

2025-01-28 00:28 UTC, SteveMacenski requested changes
Very close to being done! Just a few small changes and I think this is good to go! 

I think after you make these changes, its worth reading through it from start to end once more just to make sure there's no additional duplication or gap missing :-)

2025-01-28 00:28 UTC, SteveMacenski commented on setup_guides/sdf/images/base-bot_1.png
Do these images change from the same ones in `urdf/images/*`? If not, you can just use those directly :-) 

Though, I'm not sure if these are actually used in the SDF tutorial anymore, so can they be deleted also for that reason?

2025-01-28 00:28 UTC, SteveMacenski commented on setup_guides/sdf/setup_sdf.rst
> +.. note:: Note that you have already setup a URDF in the previous tutorials but will also need to setup a SDF. URDF is used to set up the robot frames and describe the robot's structure for run-time
Remove from here, this is already stated in the URDF tutorial and we can assume that folks that are going through this are going sequentially. If they're cherry-picking which to look at, then we can assume they know about URDF vs SDF already to know which they care about

2025-01-28 00:28 UTC, SteveMacenski commented on setup_guides/sdf/setup_sdf.rst
> +SDF is a specific file for simulators, like Gazebo, that describes the simulator environment, model (including its frames and Gazebo-specific information), and appropriate plugins. The SDF that we wi
```suggestion
SDF is a file format for simulators, like Gazebo, that describes the simulator environment, models (including its links, connections, and physics simulator metadata), and appropriate plugins. The SDF that we will make is for modern Gazebo, but there are other simulator options such as Open3D Engine or Isaac Sim.
```

2025-01-28 00:28 UTC, SteveMacenski commented on setup_guides/sdf/setup_sdf.rst
> +We can also use our SDF with the robot_state_publisher but the following package would be required to do that:
```suggestion
We can also use our SDF with the ``robot_state_publisher`` using the following package would be required to do that:
```

Please also show the code for using that package + SDF for the robot state publisher if we're going to make a comment like that

2025-01-28 00:28 UTC, SteveMacenski commented on setup_guides/sdf/setup_sdf.rst
> +Here is the SDF version of the URDF code:
Please provide just the SDF code from the URDF. The imu, diff drive, sensor plugins are covered by later tutorials for adding in and explaining them, so they shouldn't appear here yet. Kind of like how the old tutorial showed setting up URDF with frames, then the odom and sensor tutorials added into it

2025-01-28 00:28 UTC, SteveMacenski commented on setup_guides/sdf/setup_sdf.rst
> +
A screen shot here would be nice

2025-01-28 00:28 UTC, SteveMacenski commented on setup_guides/sensors/setup_sensors_gz.rst
> +In the code snippet above we set the sensor values of lidar_link to the simulated lidar's scan and range properties and set /scan as the topic to which it will publish the sensor_msgs/LaserScan messa
```suggestion
In the code snippet above we set the sensor values of lidar_link to the simulated lidar's scan and range properties and set ``/scan`` as the topic to which it will publish the ``sensor_msgs/LaserScan`` messages.
```

2025-01-28 00:28 UTC, SteveMacenski commented on setup_guides/sensors/setup_sensors_gz.rst
> +In the code snippet above we set the sensor values of camera_link to the simulated depth camera's properties and configure the sensor such that it will publish sensor_msgs/Image and sensor_msgs/Point
```suggestion
In the code snippet above we set the sensor values of camera_link to the simulated depth camera's properties and configure the sensor such that it will publish sensor_msgs/Image and ``sensor_msgs/PointCloud2`` messages to `/depth_camera/image_raw`` and ``/depth_camera/points`` topics respectively.
```

2025-01-28 16:50 UTC, Amronos commented on setup_guides/sdf/setup_sdf.rst
> +Here is the SDF version of the URDF code:
Sorry, that was done by accident.
Fixed in [cebd588](https://github.com/ros-navigation/docs.nav2.org/pull/618/commits/cebd588795e48e23f2a7b9a08970c054dfd4c9e1).

2025-01-28 16:53 UTC, Amronos commented on setup_guides/sdf/setup_sdf.rst
> +We can also use our SDF with the robot_state_publisher but the following package would be required to do that:
Done in [cebd588](https://github.com/ros-navigation/docs.nav2.org/pull/618/commits/cebd588795e48e23f2a7b9a08970c054dfd4c9e1).

> Please also show the code for using that package + SDF for the robot state publisher if we're going to make a comment like that

By that I just meant that one can pass a SDF file to ``robot_state_publisher`` and it will work similar to a URDF file. I have shown how to do this in the ``Build and Launch`` section.

2025-01-28 16:54 UTC, Amronos commented on setup_guides/sdf/setup_sdf.rst
> +.. note:: Note that you have already setup a URDF in the previous tutorials but will also need to setup a SDF. URDF is used to set up the robot frames and describe the robot's structure for run-time
Done in [cebd588](https://github.com/ros-navigation/docs.nav2.org/pull/618/commits/cebd588795e48e23f2a7b9a08970c054dfd4c9e1).

2025-01-28 20:16 UTC, SteveMacenski requested changes
Hopefully the last round!

2025-01-28 20:16 UTC, SteveMacenski commented on setup_guides/odom/setup_robot_localization.rst
> +To understand how ``robot_localization`` is configured and understand the reasoning behind the config have a look at `Configuring robot_localization <http://docs.ros.org/en/melodic/api/robot_localiza
Please readd the bit you deleted in https://github.com/ros-navigation/docs.nav2.org/pull/618/commits/a8c25ada14d75f4b64ba6f2e05096322c4263ca3, but I agree that we should point to those docs (and we do right below this in the `seealso`).

2025-01-28 20:16 UTC, SteveMacenski commented on setup_guides/sdf/setup_sdf.rst
> +We can also use our SDF with the robot_state_publisher using the following package:
```suggestion
We can also use our SDF with the robot_state_publisher using the following package. You will see how to do this in the tutorial below.
```

2025-01-28 20:16 UTC, SteveMacenski commented on setup_guides/sdf/setup_sdf.rst
> +For now the SDF will pretty much be a copy of the URDF code converted into SDFormat. Changes between the two descriptions will happen when we start adding various plugins and sensors in the next tuto
```suggestion
For now the SDF will pretty much be a copy of the URDF code converted into SDFormat. Changes between the two descriptions will happen when we start adding various plugins and sensors in the next tutorials. We also add in physical properties needed by the simulator such as the ineria, mass, and material.
```

2025-01-28 20:16 UTC, SteveMacenski commented on setup_guides/odom/setup_odom_gz.rst
> +
Quick change to complete this page:
* Have the section as any other section
* Leave the "Create a world directory..." like any other
* The world file is shown below but can also be found on the tutorial at <insert hyperlink>. 
* Move the `.. rst-class:: content-collapse` to just surrent the code block (also that code block might technically need to be listed as a new section for the title of the collapsed block, but that's just a quirk of the RST and not how its read by users)
* The stuff below the collapsed code block should not be in the collapsed block ("We also have to add the..." bit)

2025-01-29 05:48 UTC, Amronos commented on setup_guides/odom/setup_robot_localization.rst
> +To understand how ``robot_localization`` is configured and understand the reasoning behind the config have a look at `Configuring robot_localization <http://docs.ros.org/en/melodic/api/robot_localiza
I felt that there was a lot of difference between what is described there and how I configured ``ekf``.
The ``robot_localization`` documentation also describes how to set up the config very well, guiding the readers step by step and explaining every decision in detail.

2025-01-29 06:06 UTC, Amronos commented on setup_guides/odom/setup_odom_gz.rst
> +
Doing this there would be 3 different sections, and so I decided to take a different approach in [375d0e7](https://github.com/ros-navigation/docs.nav2.org/pull/618/commits/375d0e74bcbb2bfd741de9252f2b1a36248a3ee8). I decide to just create a link to the world file and delete the code block.

2025-01-29 18:26 UTC, SteveMacenski commented on setup_guides/odom/setup_robot_localization.rst
> +To understand how ``robot_localization`` is configured and understand the reasoning behind the config have a look at `Configuring robot_localization <http://docs.ros.org/en/melodic/api/robot_localiza
That does make sense and I actually agree with you :-)

My only concern is that the docs link is w.r.t. ROS 1 Melodic, which is EOL and I'm not sure how much longer that URL is going to be online. To be honest though, there's enough other web docs that mirror that so I suppose that's OK.

2025-01-29 18:28 UTC, SteveMacenski approved these changes
Great, I crazy appreciate your time and energy here! I know it was a few rounds and I was a bit picky since this is some of the first docs users see -- and it is very acknowledged.

I'm going to post on ROS Discourse and LinkedIn about this update, can you share with me your Discourse handle / linkedin profile so I can make sure I give you credit where credit is due? 

This is really fantastic and let me know if you're interested in working on something else in the code or docs! I'm happy to help you find some other contribution :-)

2025-01-30 10:41 UTC, Amronos commented
> Great, I crazy appreciate your time and energy here! I know it was a few rounds and I was a bit picky since this is some of the first docs users see -- and it is very acknowledged.

Thanks!

> I'm going to post on ROS Discourse and LinkedIn about this update, can you share with me your Discourse handle / linkedin profile so I can make sure I give you credit where credit is due?

My discourse handle would be ``@amronos``, I don't have a LinkedIn account.

> This is really fantastic and let me know if you're interested in working on something else in the code or docs! I'm happy to help you find some other contribution :-)

I would love to! One thing you have already told me to do is update ``nav2_bringup`` with composition for Gazebo.

2025-01-30 16:59 UTC, merged